import pickle
import pandas as pd
import yfinance as yf
import numpy as np
import warnings
warnings.filterwarnings('ignore')

print('Loading latest universe generated by the V6 Mega Backtest...')
with open('.tmp/cached_universes.pkl', 'rb') as f:
    cached = pickle.load(f)
    universe_at_dict = cached['universe_at']
    all_tuples = cached['all_tuples']

latest_rp = max(universe_at_dict.keys())
active_pairs_set = universe_at_dict[latest_rp]
print(f'Latest Universe Refresh Date: {latest_rp}')
print(f'Total Active Pairs in Universe: {len(active_pairs_set)}\n')

symbols_to_fetch = set()
active_pairs_info = []

for u_a, u_b in active_pairs_set:
    for t_a, t_b, l_a, l_b in all_tuples:
        if t_a == u_a and t_b == u_b:
            symbols_to_fetch.add(u_a)
            symbols_to_fetch.add(u_b)
            # l_a and l_b are the UNIVERSAL MULTIPLIERS (e.g. 1, 1)
            active_pairs_info.append((u_a, u_b, l_a, l_b))
            break

print('Fetching Live Prices via yfinance (bypassing broker API)...')
tickers = [s + '.NS' for s in symbols_to_fetch]
raw_yf = yf.download(tickers, period='1d', auto_adjust=True, progress=False, group_by='ticker')

live_prices = {}
for s in symbols_to_fetch:
    try:
        # Properly parse single ticker vs multi ticker download structure
        if len(symbols_to_fetch) == 1:
            live_prices[s] = float(raw_yf['Close'].dropna().iloc[-1])
        else:
            live_prices[s] = float(raw_yf[s + '.NS']['Close'].dropna().iloc[-1])
    except:
        pass

def load_continuous(sym):
    df = pd.read_csv(f'.tmp/5y_data/{sym}_5Y.csv')
    df.columns = [c.strip() for c in df.columns]
    df['FH_TIMESTAMP'] = pd.to_datetime(df['FH_TIMESTAMP'], format='%d-%b-%Y', errors='coerce')
    df['FH_EXPIRY_DT'] = pd.to_datetime(df['FH_EXPIRY_DT'], format='%d-%b-%Y', errors='coerce')
    df = df.dropna(subset=['FH_TIMESTAMP', 'FH_EXPIRY_DT']).sort_values('FH_TIMESTAMP')
    c = df.loc[df.groupby('FH_TIMESTAMP')['FH_EXPIRY_DT'].idxmin()].copy()
    c['FH_MARKET_LOT'] = c['FH_MARKET_LOT'].replace(0, np.nan).ffill().bfill()
    return c[['FH_TIMESTAMP', 'FH_CLOSING_PRICE', 'FH_MARKET_LOT']].set_index('FH_TIMESTAMP')

print('-'*90)
print(f'| {"PAIR":<22} | {"RAW Z":<8} | {"CORR(60)":<8} | {"ACTUAL SSS":<10} | {"DECISION":<8} |')
print('-'*90)

results = []
for sym_a, sym_b, u_lots_a, u_lots_b in active_pairs_info:
    if sym_a not in live_prices or sym_b not in live_prices:
        continue
        
    try:
        c_a = load_continuous(sym_a)
        c_b = load_continuous(sym_b)
        
        merged = c_a.join(c_b, how='inner', lsuffix='_A', rsuffix='_B')
        
        # This is exactly how execution/systems/pairs_system.py perfectly evaluates!
        # First, we identify the specific FNO lots at every point in time
        la = merged['FH_MARKET_LOT_A']
        lb = merged['FH_MARKET_LOT_B']
        
        # Second, we multiply the FNO lots by the Universal Multiplier
        mult_a_hist = u_lots_a * la
        mult_b_hist = u_lots_b * lb
        
        # Third, evaluate the historical total spread
        merged['SPREAD'] = (mult_a_hist * merged['FH_CLOSING_PRICE_A']) - (mult_b_hist * merged['FH_CLOSING_PRICE_B'])
        
        recent = merged.tail(60)
        mean_spread = recent['SPREAD'].mean()
        std_spread = recent['SPREAD'].std()
        
        if pd.isna(std_spread) or std_spread == 0:
            continue
            
        # LIVE EVALUATION: MUST USE EXACT SAME LOGIC
        p_a = live_prices[sym_a]
        p_b = live_prices[sym_b]
        
        # Live FNO lot size is the last known one
        live_la = la.iloc[-1]
        live_lb = lb.iloc[-1]
        
        live_mult_a = u_lots_a * live_la
        live_mult_b = u_lots_b * live_lb
        
        live_spread = (live_mult_a * p_a) - (live_mult_b * p_b)
        
        # Bug-Free Z-Score!
        live_z = (live_spread - mean_spread) / std_spread
        
        ret_a  = merged['FH_CLOSING_PRICE_A'].pct_change()
        ret_b  = merged['FH_CLOSING_PRICE_B'].pct_change()
        corr   = ret_a.tail(60).corr(ret_b.tail(60))
        corr   = max(0.0, float(corr)) if not pd.isna(corr) else 0.0

        sss = abs(live_z) * (1.0 + corr)
        results.append((sym_a, sym_b, live_z, corr, sss))
    except Exception as e:
        pass

results = sorted(results, key=lambda x: x[4], reverse=True)

valid_trades = 0
for a, b, z, corr, sss in results:
    if sss >= 2.0:
        action = 'ENTER V6'
        valid_trades += 1
    elif sss >= 1.5:
        action = 'WATCH'
    else:
        continue # skip boring trades
        
    print(f'| {a[:11]+"/"+b[:11]:<22} | {z:<+8.2f} | {corr:<8.2f} | {sss:<10.2f} | {action:<8} |')

print('-'*90)
if valid_trades == 0:
    print('NO TRADES CURRENTLY MEETING SSS >= 2.0 THRESHOLD')
else:
    print(f'FOUND {valid_trades} BUG-FREE V6 TRADES READY FOR EXECUTION')
